url: http://gomegawatt.com/
baseurl:

# Site settings
title: Megawatt Labs
email: stevenmaguire@gmail.com
safe_email: "&#104;&#101;&#108;&#108;&#111;&#064;&#103;&#111;&#109;&#101;&#103;&#097;&#119;&#097;&#116;&#116;&#046;&#099;&#111;&#109;"
description: "Megawatt Labs is the nervous center of your advertising operations. Our team integrates technology with your business objectives and consumer data in order to let your creative reach the right audiences."


# Color settings (hex-codes without the leading hash-tag)
color:
  primary: fed136
  secondary: fec503
  secondary-dark: 333

# Team names, titles and social links
people:
- name: Chris VanKula
  image: chris.jpg
  position: Media and Operations
  social:
    - title: twitter
      url: https://twitter.com/stevenmaguire
    - title: linkedin
      url: https://www.linkedin.com/pub/chris-vankula/0/363/898

- name: Andy Angelos
  image: andy.jpg
  position: Really Big Ego
  social:
    - title: instagram
      url: https://instagram.com/andyangelos
    - title: linkedin
      url: https://www.linkedin.com/in/andyangelos

- name: Steven Maguire
  image: steven.jpg
  position: Product and Technology
  social:
    - title: twitter
      url: https://twitter.com/stevenmaguire
    - title: linkedin
      url: https://linkedin.com/in/stevenmaguire
    - title: github
      url: https://github.com/stevenmaguire


# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: http://twitter.com/jekyllrb
  - title: facebook
    url:
  - title: stack-overflow
    url: http://stackoverflow.com/questions/tagged/jekyll
  - title: bitbucket
    url: http://bitbucket.org/jekyll
  - title: github
    url: http://github.com/megawattlabs

exchanges:
  - name: admeta
  - name: adscale
  - name: adconductor
  - name: aol
  - name: casale
  - name: switch
  - name: cox-digital-solutions
  - name: double-click
  - name: federated-media
  - name: gumgum
  - name: live-intent
  - name: openx
  - name: pubmatic
  - name: pulsepoint
  - name: rubicon
  - name: smart
  - name: yield-lab
  - name: yield-partners
  - name: nexage
  - name: improve-digital
  - name: appnexus

# Postal address (add as many lines as necessary)
address:
  - line: West Loop
  - line: "Chicago, IL 60606"

# Build settings
markdown: kramdown
permalink: pretty
