url: http://gomegawatt.com/
baseurl:

# Site settings
title: Megawatt Labs
email: stevenmaguire@gmail.com
safe_email: "&#104;&#101;&#108;&#108;&#111;&#064;&#103;&#111;&#109;&#101;&#103;&#097;&#119;&#097;&#116;&#116;&#046;&#099;&#111;&#109;"
description: "Write an awesome description for your new site here. You can edit this line in _config.yml. It will appear in your document head meta (for Google search results) and in your feed.xml site description."


# Color settings (hex-codes without the leading hash-tag)
color:
  primary: fed136
  secondary: fec503
  secondary-dark: 333

# Team names, titles and social links
people:
- name: Chris VanKula
  image: chris.jpg
  position: Media and Operations
  social:
    - title: twitter
      url: https://twitter.com/stevenmaguire
    - title: linkedin
      url: https://www.linkedin.com/pub/chris-vankula/0/363/898

- name: Andy Angelos
  image: andy.jpg
  position: Really Big Ego
  social:
    - title: instagram
      url: https://instagram.com/andyangelos
    - title: linkedin
      url: https://www.linkedin.com/in/andyangelos

- name: Steven Maguire
  image: steven.jpg
  position: Product and Technology
  social:
    - title: twitter
      url: https://twitter.com/stevenmaguire
    - title: linkedin
      url: https://linkedin.com/in/stevenmaguire
    - title: github
      url: https://github.com/stevenmaguire


# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: http://twitter.com/jekyllrb
  - title: facebook
    url:
  - title: stack-overflow
    url: http://stackoverflow.com/questions/tagged/jekyll
  - title: bitbucket
    url: http://bitbucket.org/jekyll
  - title: github
    url: http://github.com/jekyll

# Postal address (add as many lines as necessary)
address:
  - line: 3481 Melrose Place
  - line: Beverly Hills, CA 90210

# Build settings
markdown: kramdown
permalink: pretty
